### PR TITLE
added openai key

### PR DESCRIPTION
**Pull request by Freedisch**
# Robocrop 

integrated DALL-E into the codebase. I used the openai_api_key to generate an image in case the user doesn't provide an image for the product.
-added dotenv package
-added openai package
-modified the item.js from the route folder at the `post` to check if an image is provided or not if an image is genrated based on the title

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
On it! I'll review the changes as soon as possible!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Looks like we have a few checks failing. Please try again and make sure they all pass.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Looks like we have a few checks failing. Please try again and make sure they all pass.

**Review by vanessa-cooper — APPROVED** [review]
Looking good! You can merge the PR now.

**Comment by Freedisch** [comment]
I took me the whole to figure out the issue 🥱

**Pull request merged**
